name:                brickDemo
version:             0.1.0.0
github:              "Fransz/brickDemo"
license:             BSD3
author:              "Frans Jaspers"
maintainer:          "fjaspers@xs4all.nl"
copyright:           "No copyright"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fransz/brickDemo#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vector
- vty
- microlens
- microlens-th
- linear

library:
  source-dirs: 
  - src

executables:
  brickDemo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brickDemo

tests:
  brickDemo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brickDemo
